### ISSUE TITLE
no fake windows appear

### ISSUE THREAD

**Issue by varefaz** [MTK911/Attiny85#6]
hi, I loaded the code on the digispark without any problem. and it seems to run without any problems. opens the powershell and starts writing.
at the end the red led lights up. but no window is opened. any ideas? thanks

**Comment by MTK911** [comment]
Hey @varefaz, you can try changing the line 11 which contains powershell opening command to notepad like this:
DigiKeyboard.println("powershell -noexit -command \"mode con cols=18 lines=1\"");
to this
DigiKeyboard.println("notepad");
It will start writing the code on notepad instead of terminal. To make sure everything is working fine copy all the typed command from notepad and manually paste it in Powershell and see the response if there is no error in code it will execute the code and powershell windows will disappear. You will see Pop-up for login after 1 minute as time is set. You can change it to make it appear faster. 

I have tested it on Windows 10 today and it is still working fine.
